<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'ThinkPad X1 Yoga Gen 8',
                'image' => 'thinkpadx1.png',
                'quantity' => 99,
                'screen' => "14inch WUXGA (1920 x 1200), IPS, Anti-Reflective, Touch, 100%sRGB, 400 nits, Narrow Bezel",
                'cpu' => '13th Generation Intel® Core™ i5-1335U Processor (E-cores up to 3.40 GHz P-cores up to 4.60 GHz)',
                'gpu' => 'Integrated Intel® Iris® Xe Graphics',
                'memory' => '256 GB SSD M.2 2280 PCIe Gen4 TLC Opal',
                'ram' => '16 GB LPDDR5-6400MHz (Soldered)',
                'battery' => '57Whr battery | Rapid Charge (60 minutes = 80% runtime), requires 65W or higher adapter',
                'size' => 'Cao x Rộng x Sâu = 15.53mm x 314.4mm x 222.3mm x / 0.61″ x 12.38″ x 8.75″',
                'weight' => '1.38kg',
                'price' => '58000000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 1,
                'description' => 'Next-level performance Powered by 13th Gen Intel® Core™ vPro® processors, the Lenovo ThinkPad X1 Yoga Gen 8 2-in-1 laptop takes multitasking to the next level. These CPUs intelligently allocate workloads to the right thread, on the right core, at the right time—which allows for better team collaboration and productivity based on how you’re actually using your device. And with Intel® Evo™ certification, you can count on consistent responsiveness, instant wake, all-day battery life, rapid charging, and intelligent video conferencing.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ThinkBook 13x Gen 2',
                'image' => 'thinkbook1.png',
                'quantity' => 50,
                'screen' => "13.3inch WQXGA (2560 x 1600), IPS, Anti-Glare, 100%sRGB, Non-touch, 400 nits, Narrow Bezel",
                'cpu' => '12th Generation Intel® Core™ i5-1235U Processor (E-cores up to 3.30 GHz P-cores up to 4.40 GHz)',
                'gpu' => 'Integrated Intel® Iris® Xe Graphics',
                'memory' => '512 GB SSD M.2 2280 PCIe Gen4 TLC',
                'ram' => ' 8 GB LPDDR5-4800MHz (Soldered)',
                'battery' => '4 cell, 56Wh',
                'size' => 'Cao x Rộng x Sâu = 12.9mm x 298mm x 209mm / 0.50" x 11.73" x 8.22"',
                'weight' => '1.21kg',
                'price' => '40200000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 2,
                'description' => 'Processor cores optimized for multitasking 12th Gen Intel® Core™ processors deliver the power you need for office work, content creation—whatever your day demands. Using a new, hybrid architecture, performance cores handle single- or lightly-threaded workloads while highly-threaded jobs go to efficient cores optimized for such work. As you focus on multitasking, Intel® Thread Director picks the best cores for each job.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'IdeaPad Flex 5i Gen 8',
                'image' => 'ideapad1.png',
                'quantity' => 34,
                'screen' => "14inch WUXGA (1920 x 1200), IPS, Anti-Reflective, Touch, 100%sRGB, 400 nits, Narrow Bezel",
                'cpu' => 'Intel® Evo™ performance with up to 13th Gen Intel® Core™ i7',
                'gpu' => 'Integrated Intel® Iris® Xe Graphics',
                'memory' => '256 GB SSD M.2 2280 PCIe Gen4 TLC Opal',
                'ram' => '16 GB LPDDR5-6400MHz (Soldered)',
                'battery' => 'Up to 15 hours* (video playback)',
                'size' => 'Cao x Rộng x Sâu = 15.53mm x 314.4mm x 222.3mm x / 0.61″ x 12.38″ x 8.75″',
                'weight' => '1.55kg',
                'price' => '25500000',
                'status' => 1,
                'discount_status' => 1,
                'discount_value' => 45,
                'category_id' => 3,
                'description' => 'Multi-core turbo power makes multitasking a breeze Lenovo Flex 5i Gen 8 features up to 13th Gen Intel® Core™ i7, from a range of CPUs specifically engineered for thin and light laptops. Multiple cores give you the power to run multiple apps seamlessly and simultaneously. You can even edit video while you video chat with the confidence your device will run cool and silent under any conditions.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoga Slim 9i Gen 7',
                'image' => 'yoga1.png',
                'quantity' => 75,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '57200000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 4,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Legion Pro 7i 16',
                'image' => 'legion1.png',
                'quantity' => 300,
                'screen' => "16inch WQXGA (2560 x 1600), IPS, Anti-Glare, Non-Touch, HDR 400, 100%sRGB, 500 nits, 240Hz, Narrow Bezel, Low Blue Light",
                'cpu' => '13th Generation Intel® Core™ i9-13900HX Processor (E-cores up to 3.90 GHz P-cores up to 5.40 GHz)',
                'gpu' => 'NVIDIA® GeForce RTX™ 4080 12GB GDDR6',
                'memory' => '512 GB SSD M.2 2280 PCIe Gen4 TLC',
                'ram' => '16 GB DDR5-5600MHz (SODIMM) - (2 x 8 GB)',
                'battery' => '4 cell, 99.9Wh',
                'size' => 'Cao x Rộng x Sâu = 21.95-25.9mm x 363.4mm x 262.15mm / 0.86″-1.01″ x 14.3″ x 10.32″',
                'weight' => '2.8kg',
                'price' => '85500000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 5,
                'description' => '13th Gen Intel® Core™ processors. Beyond performance. Intels latest hybrid architecture, paired with industry-leading features, delivers the ultimate gaming experience. Stream, create and compete at the highest levels – 13th Gen Intel Core processors push your gameplay beyond performance, giving you the power to do it all.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoga 6 Gen 8 (13" AMD)',
                'image' => 'yoga1.png',
                'quantity' => 45,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '67200000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 4,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoga 9i Gen 8 (14" Intel)',
                'image' => 'yoga1.png',
                'quantity' => 80,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '59200000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 4,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoga Slim 9i Gen 7 (14" Intel)',
                'image' => 'yoga1.png',
                'quantity' => 75,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '50000000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 4,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoga 7i Gen 8 (16" Intel)',
                'image' => 'yoga1.png',
                'quantity' => 45,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '49200000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 4,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Yoga 7i Gen 8 (14" Intel)',
                'image' => 'yoga1.png',
                'quantity' => 35,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '76500000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 4,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ThinkPad P14s Gen 3 (14inch AMD)',
                'image' => 'yoga1.png',
                'quantity' => 75,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '57200000',
                'status' => 0,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 1,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'ThinkPad P15v Gen 3 (15inch AMD)',
                'image' => 'yoga1.png',
                'quantity' => 75,
                'screen' => "14inch WQUXGA (3840 x 2400), OLED, Glare, Touch, 100%DCI-P3, 400 nits, 60Hz, Narrow with Glass",
                'cpu' => '12th Generation Intel® Core™ i7-1280P Processor (E-cores up to 3.60 GHz P-cores up to 4.80 GHz)',
                'gpu' => 'Integrated Graphics',
                'memory' => '512 GB SSD M.2 2242 PCIe Gen4 TLC',
                'ram' => '16 GB LPDDR5-5600MHz (Soldered)',
                'battery' => '4 Cell Li-Polymer 75Wh',
                'size' => 'Cao x Rộng x Sâu = As thin as 14.9mm x 315mm x 214.4mm / 0.6″ x 12.52″ x 9.06″',
                'weight' => '1.37kg',
                'price' => '57200000',
                'status' => 1,
                'discount_status' => 0,
                'discount_value' => 0,
                'category_id' => 1,
                'description' => 'Think sustainably, act responsibly. Make the sustainable choice with an ultraslim laptop crafted from recycled materials and green packaging*, endorsed with ENERGY STAR® certification, and EPEAT™ Silver registered in the US. Carbon-neutral certified**, the Yoga Slim 9i truly exemplifies the pinnacle of premium, portable, sustainable, power. Think sustainably, do responsibly.',
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
